site_name: Mad-Assembler
site_author: TeBe
site_description: "Mad-Assembler Dokumentacja"
site_keyword: "cross-compiler"

repo_url: https://github.com/tebe6502/Mad-Assembler

theme:
    name: readthedocs
    highlightjs: true
    hljs_style: dark
    hljs_languages:
        - armasm

nav:
    - Wprowadzenie: wprowadzenie.md
    - Sposób użycia: sposob-uzycia.md
    - Sparta DOS X: sparta-dos.md
    - Mnemoniki: mnemoniki.md
    - Detekcja CPU: detekcja-cpu.md
    - Banki pamięci: banki-pamieci.md
    - Kod relokowalny: kod-relokowalny.md
    - Typy: typy.md
    - Składnia: skladnia.md
    - Przykłady: przyklady.md
    - Projekty: projekty.md
