site_name: Mad-Assembler
site_author: TeBe
site_description: "Mad-Assembler Documentation"
site_keyword: "cross-compiler"

repo_url: https://github.com/tebe6502/mad-assembler-en-mkdocs/

theme:
    name: readthedocs
    highlightjs: true
    hljs_style: dark
    hljs_languages:
        - armasm

nav:
    - Introduction: introduction.md
    - Usage: usage.md
    - Assembly control: control.md
    - Sparta DOS X: spartados.md
    - Syntax: syntax.md
    - Labels: labels.md
    - Mnemonics: mnemonics.md
    - Macro commands: macrocommands.md
    - Pseudo-commands: pseudocommands.md
    - Directives: directives.md
    - Local area: local.md
    - Procedures: procedures.md
    - Macros: macros.md
    - Directives that generate code: directivescode.md
    - Arrays: arrays.md
    - Data types: types.md
    - CPU detection: detectioncpu.md
    - Memory banks: memorybanks.md
    - Relocatable code: coderelocatable.md
    - Examples: examples.md
    - Projects: projects.md
